export const SET_SKIN = "SET_SKIN";
export const UPDATE_SKIN = "UPDATE_SKIN";

export const SET_CONTACT = "SET_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";

export const SET_EDUCATION = "SET_EDUCATION";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_REQUEST_FAILED = "SIGN_IN_REQUEST_FAILED";
export const SIGN_IN_REQUEST_SUCCESS = "SIGN_IN_REQUEST_SUCCESS";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_REQUEST_FAILED = "SIGN_UP_REQUEST_FAILED";
export const SIGN_UP_REQUEST_SUCCESS = "SIGN_UP_REQUEST_SUCCESS";

export const SIGN_OUT_REQUEST = "SIGN_OUT_REQUEST";
export const SIGN_OUT_REQUEST_FAILED = "SIGN_OUT_REQUEST_FAILED";
export const SIGN_OUT_REQUEST_SUCCESS = "SIGN_OUT_REQUEST_SUCCESS";

export const REMOVE_ERROR = "REMOVE_ERROR" ;
